# Page settings
baseurl = "localhost:1313"
title = "Web3 Research Lab"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Prof. Dr. Dr. Momtaz"
  description = "TUM Web3 Research Lab"
  email = "karin.papavlassopoulos(at)tum.de"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Web3 Research Lab"
    home = "Home"
    work = "Partners"
    testimonials = "Testimonials"
    services = "Education"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Web3 Research Lab"
    subtitle = 'We bundle Germany’s most productive blockchain researchers and provide teaching, talent sourcing, and advisory for students, companies, and policymakers, respectively.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "MunichX"
    description = "Our MunichX accelerator program aims to support and back Web3 pioneers by providing financial resources, extensive expertise, and a network to assist founders in prioritizing their technological development."
    url = "https://www.munichx.net"
    button = "Go to MunichX"
    icon = "icon-rocket"
    img = "img_9.jpg"

  [[params.intro.item]]
    title = "Blockchain Talents @ TUM"
    description = "Blockchain Talents @ TUM  connects some of the brightest tech and business minds in Europe to corporate partners and industry-led initiatives."
    url = "./documents/TUM_Blockchain_Talents.pdf"
    button = "Learn more"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Workshops and Education"
    description = "Our leading digital assets education has brought cutting-edge topics grounded in current research debates to close to 1,000 students. Our stakeholders include undergraduate, graduate, and doctoral students, as well as corporate clients through our workshop formats, ranging from early-career blockchain enthusiasts to C-level executives seeking updates on overarching trends in web3."
    url = "#services"
    button = "Learn more (LINK MISSING)"
    icon = "icon-bulb"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Partners"
    description = "Our partners support us in exploring the future of our digital society."
    
    [[params.work.row]]
      img = "Deutsche_Bundesbank_Logo3.jpg"
      alt = "Deutsche Bundesbank"
      title = "Deutsche Bundesbank"
      #subtitle = ""

    [[params.work.row]]
      img = "Google_Logo.jpg"
      alt = "Google"
      title = "Google"
      #subtitle = ""
 
    [[params.work.row]]
      img = "FIRM_Logo1.jpg"
      alt = "Frankfurter Institut für Risikomanagement und Regulierung"
      title = "FIRM"
      #subtitle = "(FIRM)"

    [[params.work.row]]
      img = "CryptoFundResearch_Logo.jpg"
      alt = "CryptoFundResearch"
      title = "CryptoFundResearch"
      #subtitle = ""

    [[params.work.row]]
      img = "Moonrock_Capital_Logo1.jpg"
      alt = "Moonrock Capital"
      title = "Moonrock Capital"
      #subtitle = ""

    [[params.work.row]]
      img = "Coinmarketcap_Logo.jpg"
      alt = "Coinmarketcap"
      title = "Coinmarketcap"
      #subtitle = ""

    [[params.work.row]]
      img = "FINDT1.jpg"
      alt = "FINDT"
      title = "FINDT"
      #subtitle = ""

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = ""


    [[params.testimonials.item]]
      quote = "&ldquo;With the Web3 Research Lab, Munich now hosts a European powerhouse to advance education and research in web3. I look forward to a flourishing web3 ecosystem in Munich.&rdquo;"
      person = 'Dr. David An, Partner at Dracoon Ventures https://www.linkedin.com/in/davidan'
      img = "David_An.jpg"
      alt = "Dr. David An"

    [[params.testimonials.item]]
      quote = "&ldquo;Prof. Momtaz and his team are doing globally leading research on blockchain in business with high practical relevance. It is great that the Web3 Research Lab provides an institutional platform to bridge academia and practice.&rdquo;"
      person = 'Paul Kammerer, CCO at Fincite https://www.linkedin.com/in/paul-kammerer-8a842861/'
      img = "Paul_Kammerer.jpg"
      alt = "Paul Kammerer"

    [[params.testimonials.item]]
      quote = "&ldquo;We are proud to have the Web3 Research Lab at TUM as our primary partner for the MunichX accelerator. They are going to play a pivotal role in helping us fostering Munich's Web3 ecosystem by supporting the most promising founders of tomorrow.&rdquo;"
      person = 'Simon Dedic, CEO & Partner at Moonrock Capital https://www.linkedin.com/in/simon-dedic-b98768140/'
      img = "Simon_Dedic.jpeg"
      alt = "Simon Dedic"

    [[params.testimonials.item]]
      quote = "&ldquo;The launch of the Web3 Research Lab and the integration of the MunichX Accelerator mark a significant step for Munich's technology ecosystem. Bringing together cutting-edge research and entrepreneurial spirit will enrich the innovation landscape, foster talent, and strengthen Munich as a location for Web3 technologies.&rdquo;"
      person = 'Florian Peter, VP at Greenfield Capital https://www.linkedin.com/in/florian-peter-2b9717a8/'
      img = "Florian_Peter.jpeg"
      alt = "Florian Peter"

    [[params.testimonials.item]]
      quote = "&ldquo;As an alum of TUM, I'm thrilled to see the TUM Web3 Research Lab driving innovation and education in the blockchain realm. TUM breeds great blockchain minds. bitsCrunch is delighted that the Web3 Research Lab is consolidating educational initiatives within and beyond the TUM ecosystem.&rdquo;"
      person = 'Vijay Pravin, Founder & CEO at bitsCrunch https://www.linkedin.com/in/vijaypravin/'
      img = "pravin.jpg"
      alt = "Vijay Pravin"
    



  # Services section
  [params.services]
    enable = true
    title = "Education"
    description = "Our leading digital assets education brings cutting-edge topics grounded in current research debates to various stakeholders. We educate students at all levels, from undergraduate to post-graduate programs, as well as corporate stakeholders, from early-career blockchain enthusiasts seeking foundational knowledge to C-level executives seeking knowledge about overarching trends in web3."

    [[params.services.item]]
      title = "Courses at TUM"
      description = "Our Blockchain Technology & Digital Assets courses at TUM are in high demand and attract regularly far more students that we can accommodate. If you are a TUM student, please check for announcement in the course catalogue at TUMonline. Also, sign up for Blockchain Talents @ TUM to stay in the loop about new courses, theses, and internship opportunities in the web3 space."
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Workshops and Executive Education"
      description = "We receive many requests from corporates to provide executive education in the form of intensive workshops, both for early-career blockchain enthusiasts to C-level executives having to cope with the fast-moving trends in Web3. If you are interested in our workshop formats, please contact us through the contact form below."
      icon = "icon-people"

    [[params.services.item]]
      title = "Online Certificates at Coursera & Co"
      description = "Our education is in high demand. Each months the number of requests for online education on Web3 technologies grows by +2,000 students. We are currently developing together with Coursera certificate programs to bring out leading TUM education to a global audience."
      icon = "icon-monitor"

    [[params.services.item]]
      title = "W3RL Working Papers"
      description = "The Web3 Research Lab is known for internationally leading research on web3. The W3RL Working Paper Series provides platform for highly specialized academic research on pressing questions of our time."
      icon = "icon-graduation-cap"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = ""

    [[params.about.item]]
      name = "Prof. Dr. Dr. Paul P. Momtaz"
      position = "Founder of Web3 RL and Professor at TUM"
      description = "Professor Momtaz’s expertise span the full range of tokenization. Wirtschaftswoche ranks him as the top researcher on digital assets in the DACH region."
      img = "momtaz.jpg"
      alt = "Prof. Dr. Dr. Paul P. Momtaz"
      social = [
        # ["icon-twitter", ""],
        ["icon-linkedin", "https://www.linkedin.com/in/paulmomtaz/"]
      ]

    [[params.about.item]]
      name = "Dr. Valerie Laturnus"
      position = "Research Associate"
      description = "Valerie’s expertise encompasses the impact of blockchain on financial markets and the use of smart contracts in various industries"
      img = "Valerie_Laturnus.jpg"
      alt = "Dr. Valerie Laturnus"
      social = [
        # ["icon-twitter", "#"],
        # ["icon-github", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/valerielaturnus/"]
      ]

    [[params.about.item]]
      name = "Martin El-Khouri"
      position = "Research Associate"
      description = "Martin’s expertise centres around the value drivers in Web3; he is a Senior Director at Bertelsmann Investments where he leads the BI Web3 Hub."
      img = "Martin_El-Khouri.jpg"
      alt = "Martin El-Khouri"
      social = [
        # ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/el-khouri-m/"]
      ]

    [[params.about.item]]
      name = "Johannes Fuchs"
      position = "Research Associate"
      description = "Johannes’s expertise includes the structure and performance of token offerings."
      img = "Johannes_Fuchs.jpeg"
      alt = "Johannes Fuchs"
      social = [
        # ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/johannes-fuchs/"]
      ]

   
    [[params.about.item]]
      name = "Hannes Urban"
      position = "Research Associate"
      description = "Hannes’s expertise is in quantitative investment research where he develops machine-learning models to predict token returns."
      img = "Hannes_Urban.jpeg"
      alt = "Hannes Urban"
      social = [
        # ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/hannes-urban-ab6411198/"]
      ]

 [[params.about.item]]
      name = "Yusuf Zhang"
      position = "Managing Director at Web3 RL"
      description = "Yusuf’s expertise is in the tokenization of real-world assets, esp. commercial real estate DAOs."
      img = "Yusuf.jpg"
      alt = "Yusuf Zhang"
      social = [
        # ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/yusufzhang/"]
      ]





  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 23
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Ongoing Projects"
      icon = "icon-code"
      from = 0
      to = 6
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Students"
      icon = "icon-people"
      from = 0
      to = 500
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Research Downloads"
      icon = "icon-book"
      from = 0
      to = 100000
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = false
    title = "Get in touch"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Arcisstr. 21, 80333 Munich, Germany"],
        ["icon-phone", "+49 (0) 89 / 289 - 25489"],
        ["icon-envelope", "web3@mgt.tum.de"],
        ["icon-globe", '<a href="http:s//web3rl.com" target="_blank">web3rl.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        # ["icon-twitter", "#twitter"],
        ["icon-youtube", "#youtube"]
      ]

[deployment]
order = [".jpg$", ".jpeg$", ".webp$", ".gif$"]

[[deployment.targets]]
name = "S3deployment"
URL = "s3://web3rl?region=eu-central-1"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf|pdf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
