baseURL = "https://w3rl.com"
title = "W3RL - Breaking Blocks and snapping' Chains"
author = "Prof. Dr. Momtaz"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.webp"
    alt = "W3RL Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Web3 Research Lab"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Germany’s most productive blockchain research center"
    meta_og_title = "W3RL"
    meta_og_type = "website"
    meta_og_url = "https://w3rl.com"
    meta_og_image = "img/logo.svg"
    meta_og_description = "Germany’s most productive blockchain research center"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
